version: "3.6"

services:
  postgres:
    build:
      context: .
      dockerfile: docker/galbana/Dockerfile
    volumes:
      - "./docker/galbana/copy:/copy"
      - "./docker/utils.sh:/copy/utils.sh"

  django:
    volumes:
      - "./docker/galbana/copy:/copy"
      - "./docker/utils.sh:/copy/utils.sh"
      - "./django_project:/django_project"

  nginx:
    volumes:
        - "./docker/galbana/copy:/copy"
        - "./docker/utils.sh:/copy/utils.sh"
