version: "3.6"

volumes:
  data:
    driver: local

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

services:
  postgres:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}:${IMAGE_TAG}
    env_file: .env
    volumes:
      - "data:/data"
      - "./.secrets/postgres:/run/secrets:ro"
    command: ["postgres"]
    ports:
      - "127.0.0.1:5432:5432"

  django:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}:${IMAGE_TAG}
    env_file: .env
    depends_on: ["postgres"]
    command: ["django"]
    volumes:
      - "./.secrets/django:/run/secrets:ro"

  nginx:
    image: ${REGISTRY_URL}/${COMPOSE_PROJECT_NAME}:${IMAGE_TAG}
    env_file: .env
    depends_on: ["django"]
    command: ["nginx"]
    volumes:
      - "./.secrets/nginx:/run/secrets:ro"
    ports:
      - "80:80"
      - "443:443"
